#!/bin/bash
#SBATCH --time=4
#SBATCH --output=output/result-4nodes.csv

# The line SBATCH --time=4 means: max exec time of the batch is 4 minutes
# When developping and debuging: use small test and small time limits
# After you can sublit Batch with 15, 30, 60, 120 minutes

source /etc/profile

module load py-mpi4py/3.1.4/gcc-12.3.0-openmpi

for ((i=0; i<5; i++)); do


    echo -n "4, 1E4, $i, "
    /usr/bin/mpirun -np 64 -map-by ppr:16:node:PE=1 -rank-by core python3 kmeans ../Data-for-Benchmark/META_DATA_S1_1E4.txt
    echo -n "4, 1E5, $i, "
    /usr/bin/mpirun -np 64 -map-by ppr:16:node:PE=1 -rank-by core python3 kmeans ../Data-for-Benchmark/META_DATA_S1_1E5.txt
    echo -n "4, 1E6, $i, "
    /usr/bin/mpirun -np 64 -map-by ppr:16:node:PE=1 -rank-by core python3 kmeans ../Data-for-Benchmark/META_DATA_S1_1E6.txt
done 